version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: avito123
      POSTGRES_DB: avito_shop
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=avito
      - DB_PASSWORD=avito123
      - DB_NAME=avito_shop
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret_key

volumes:
  postgres_data: